# Generated by Django 2.2.1 on 2019-08-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190809_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsave',
            name='time_saved',
        ),
    ]
