# Generated by Django 2.2.1 on 2019-08-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190828_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefollow',
            name='timestamp',
        ),
    ]
