// Why action types are declared as string constants in a separate file
// https://redux.js.org/recipes/reducing-boilerplate#actions

export const POST_LIST_LOADING = 'POST_LIST_LOADING';

export const POST_LIST_LOADED = 'POST_LIST_LOADED';

export const POST_LIST_MORE_LOADED = 'POST_LIST_MORE_LOADED';

export const POST_LIST_ERROR = 'POST_LIST_ERROR';

export const UPDATE_POST = 'UPDATE_POST';

export const LOAD_POST_DETAIL = 'LOAD_POST_DETAIL';

export const UPDATE_POST_DETAIL = 'UPDATE_POST_DETAIL';

export const POST_DETAIL_COMMENT_COUNT_ADD = 'POST_DETAIL_COMMENT_COUNT_ADD';

export const POST_DETAIL_COMMENT_COUNT_SUBTRACT = 'POST_DETAIL_COMMENT_COUNT_SUBTRACT';

export const DELETE_POST = 'DELETE_POST';

export const GET_ERRORS = 'GET_ERRORS';

export const CREATE_MASSAGE = 'CREATE_MASSAGE';

export const USER_LOADING = 'USER_LOADING';

export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_SAVE_POST = 'USER_SAVE_POST';

export const USER_FOLLOW = 'USER_FOLLOW';

export const USER_UPDATE = 'USER_UPDATE';

export const LOAD_PROFILE = 'LOAD_PROFILE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const UPDATE_PROFILE_POSTS = 'UPDATE_PROFILE_POSTS';

export const REMOVE_PROFILE = 'REMOVE_PROFILE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const CURRENT_POST_ID = 'CURRENT_POST_ID';

export const COMMENT_LIST_LOADING = 'COMMENT_LIST_LOADING';

export const COMMENT_LIST_LOADED = 'COMMENT_LIST_LOADED';

export const COMMENT_LIST_MORE_LOADED = 'COMMENT_LIST_MORE_LOADED';

export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR';

export const REMOVE_COMMENT_LIST = 'REMOVE_COMMENT_LIST';

export const REPLIES_LIST_LOADING = 'REPLIES_LIST_LOADING';

export const REPLIES_LIST_LOADED = 'REPLIES_LIST_LOADED';

export const REPLIES_LIST_ERROR = 'REPLIES_LIST_ERROR';

export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_REPLY = 'ADD_REPLY';

export const UPDATE_COMMENT = 'UPDATE_COMMENT';

export const UPDATE_REPLY = 'UPDATE_REPLY';

export const DELETE_COMMENT = 'DELETE_COMMENT';

export const DELETE_REPLY = 'DELETE_REPLY';

export const ADD_COMMENT_FORM_INFO = 'ADD_COMMENT_FORM_INFO';

export const REMOVE_COMMENT_FORM_INFO = 'REMOVE_COMMENT_FORM_INFO';

export const USER_LIST_LOADING = 'USER_LIST_LOADING';

export const USER_LIST_LOADED = 'USER_LIST_LOADED';

export const USER_LIST_ERROR = 'USER_LIST_ERROR';

export const REMOVE_USER_LIST = 'REMOVE_USER_LIST';

export const POST_SLIDER_LOADING = 'POST_SLIDER_LOADING';

export const POST_SLIDER_LOADED = 'POST_SLIDER_LOADED';

export const POST_SLIDER_MORE_LOADED = 'POST_SLIDER_MORE_LOADED';

export const POST_SLIDER_ERROR = 'POST_SLIDER_ERROR';

export const REMOVE_POST_SLIDER = 'REMOVE_POST_SLIDER';
